import 'package:flutter/painting.dart';

/// A ready-made floor / backdrop for the product studio
/// (assets/surfaces, generated by tool/make_surfaces.py).
class StudioSurface {
  const StudioSurface(
    this.id,
    this.ar,
    this.en,
    this.average, {
    this.glossy = false,
    this.floor = 0.42,
  });

  final String id;
  final String ar;
  final String en;

  /// Average color of the scene, used to match the product's light.
  final Color average;

  /// Polished surfaces show a reflection under the product.
  final bool glossy;

  /// Where the table meets the wall (0 – 1), or null for a seamless
  /// studio backdrop.
  final double? floor;

  String get asset => 'assets/surfaces/$id.jpg';

  String label(bool arabic) => arabic ? ar : en;
}

const studioSurfaces = <StudioSurface>[
  StudioSurface('white_marble', 'رخام أبيض', 'White marble', Color(0xFFD6D4CF),
      glossy: true),
  StudioSurface('black_marble', 'رخام أسود', 'Black marble', Color(0xFF2B2A29),
      glossy: true),
  StudioSurface('white_counter', 'طاولة بيضاء', 'White counter',
      Color(0xFFE1E1DF),
      glossy: true, floor: 0.46),
  StudioSurface('oak_wood', 'خشب فاتح', 'Oak wood', Color(0xFFA27D5B)),
  StudioSurface('walnut_wood', 'خشب داكن', 'Walnut wood', Color(0xFF583A26)),
  StudioSurface('linen', 'قماش كتان', 'Linen', Color(0xFFD3C8B6), floor: 0.40),
  StudioSurface('concrete', 'إسمنت', 'Concrete', Color(0xFFA2A19D)),
  StudioSurface('studio_cream', 'استوديو كريمي', 'Cream studio',
      Color(0xFFF7EEDD),
      floor: null),
  StudioSurface('studio_pink', 'استوديو وردي', 'Pink studio', Color(0xFFFCD6E1),
      floor: null),
  StudioSurface('studio_blue', 'استوديو أزرق', 'Blue studio', Color(0xFFC2DEF6),
      floor: null),
  StudioSurface('studio_sage', 'استوديو أخضر', 'Sage studio', Color(0xFFD0E2C9),
      floor: null),
  StudioSurface('studio_dark', 'استوديو داكن', 'Dark studio', Color(0xFF212024),
      floor: null),
];
